version: "3.9"
services:
  mysql:
    image: mysql:8
    container_name: db_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql

  ev_station_service:
    build: .
    container_name: ev_station_service
    restart: always
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mysql://root:root@mysql:3306/mydb"

volumes:
  mysql_data:
