# Stage 1: Build NestJS
FROM node:20-alpine AS builder
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Production
FROM node:20-alpine
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --only=production
COPY prisma ./prisma
COPY --from=builder /usr/src/app/dist ./dist
EXPOSE 3000

CMD ["sh", "-c", "npx prisma generate && node dist/main.js"]
