services:
  payment-service:
    build: .
    container_name: payment-service
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:15
    container_name: payment-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: ev_payment_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always