export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    VERIFY: '/auth/verify',
    RESEND_CODE: '/auth/resend-code',
    LOGOUT: '/auth/logout',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    REFRESH: '/auth/refresh-token',
    SOCIAL: '/auth/login/oauth',
    LINK_PROVIDER: '/auth/link-provider',
    UNLINK_PROVIDER: '/auth/unlink-provider',
  },
  USER: {
    ME: '/auth/me',
    PROFILE: '/users/:user_id',
    UPDATE_PROFILE: '/users/:user_id',
    CHANGE_PASSWORD: '/users/:user_id/change-password',
    DEACTIVATE: '/users/:user_id/deactivate',
    EXPORT_DATA: '/users/:user_id/export-data',
    ERASE_DATA: '/users/:user_id/erase',
    LIST: '/users',
  },
  VEHICLE: {
    ADD: '/users/:user_id/vehicles',
    LIST: '/users/:user_id/vehicles',
    DETAIL: '/vehicles/:vehicle_id',
    UPDATE: '/vehicles/:vehicle_id',
    DELETE: '/vehicles/:vehicle_id',
  },
  STATION: {
    SEARCH: '/stations',
    DETAIL: '/stations/:id',
    CONNECTORS: '/stations/:id/connectors',
    PRICING: '/stations/:id/pricing',
    REPORT_ISSUE: '/stations/:id/report-issue',
  },
  BOOKING: {
    CHECK: '/booking/check',
    CREATE: '/booking',
    LIST: '/booking/user/:user_id',
    DETAIL: '/booking/:reservation_id',
    UPDATE: '/booking/:reservation_id',
    CANCEL: '/booking/:reservation_id',
    PREVIEW_COST: '/booking/:reservation_id/preview-cost',
    FINALIZE: '/booking/:reservation_id/finalize',
  },
  CHARGING: {
    INITIATE: '/charging/initiate',
    START: '/charging/start',
    STOP: '/charging/:session_id/stop',
    PAUSE: '/charging/:session_id/pause',
    RESUME: '/charging/:session_id/resume',
    DETAIL: '/charging/:session_id',
    TELEMETRY: '/charging/:session_id/telemetry',
  },
  WALLET: {
    BALANCE: '/payments/wallet/:user_id',
    TOPUP: '/payments/wallet/topup',
    TRANSACTIONS: '/wallets/:user_id/transactions',
    WITHDRAW: '/wallets/:user_id/withdraw',
  },
  PAYMENT: {
    CREATE: '/payments/transaction',
    DETAIL: '/payments/transaction/:id',
    LIST: '/payments/user/:user_id/payments',
  },
  NOTIFICATION: {
    LIST: '/notifications/:user_id',
    MARK_READ: '/notifications/:notification_id/read',
    MARK_ALL_READ: '/notifications/:user_id/read-all',
  },
};