version: "3.8"

services:
### Station-service
  station-database:
    image: mysql:8.0
    container_name: station-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: station_service
    ports:
      - "3306:3306"
    volumes:
      - station-data:/var/lib/mysql
      - ../../services/station-service/seeds/data.sql:/docker-entrypoint-initdb.d/data.sql
    command: >
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --init-connect='SET NAMES utf8mb4;'
      --skip-character-set-client-handshake
    networks:
      - kong-net

  station-service:
    build:
      context: ../../services/station-service
      dockerfile: Dockerfile
    image: station-service:v1.0.0
    container_name: station-service
    restart: always
    depends_on:
      - station-database
    ports:
      - "8386:3000"
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      DATABASE_URL: "mysql://root:root@station-database:3306/station_service"
    networks:
      - kong-net

## Charging-service
  reservation-database:
    image: mysql:8.0
    container_name: reservation-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ev_charging
    ports:
      - "3307:3306"
    volumes:
      - reservation-data:/var/lib/mysql
      - ../../services/charging-control-service/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p123456"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - kong-net

  reservation-service:
    build:
      context: ../../services/charging-control-service
      dockerfile: Dockerfile
    image: reservation-service:v1.0.0
    container_name: reservation-service
    depends_on:
      reservation-database:
        condition: service_healthy
    environment:
      DB_HOST: reservation-database
      DB_USER: root
      DB_PASSWORD: 123456
      DB_NAME: ev_charging
      DB_PORT: 3306
      RATE_PER_KWH: 20000
      PORT: 4002
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - "4002:4002"
    restart: on-failure
    networks:
      - kong-net

## Payment service
  payment-service:
    build:
      context: ../../services/payment-service
      dockerfile: Dockerfile
    image: payment-service:v1.0.0
    container_name: payment-service
    ports:
      - "8080:8080"
    env_file: ../../services/payment-service/.env
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
    restart: always
    networks:
      - kong-net

  postgres:
    image: postgres:15
    container_name: payment-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: ev_payment_db
    ports:
      - "5432:5432"
    volumes:
      - payment-db-data:/var/lib/postgresql/data
      - ../../services/payment-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - kong-net

  # PostgreSQL for Auth Service
  postgres-auth:
    image: postgres:15-alpine
    container_name: ev-postgres-auth
    environment:
      POSTGRES_DB: ev_auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres-auth-data:/var/lib/postgresql/data
      - ../../database/schema/ev_auth_db.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ../../database/seeds/seed-auth.sql:/docker-entrypoint-initdb.d/02-seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kong-net

  # pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ev-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@evcharging.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres-auth
    networks:
      - kong-net

  # PostgreSQL for User Service
  postgres-user:
    image: postgres:15-alpine
    container_name: ev-postgres-user
    environment:
      POSTGRES_DB: ev_user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
      - ../../database/schema/ev_user_db.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ../../database/seeds/seed-user.sql:/docker-entrypoint-initdb.d/02-seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kong-net

# Auth Service
  ev-auth-service:
    build:
      context: ../../services/auth-service
      dockerfile: Dockerfile
    image: auth-service:v1.0.0
    container_name: ev-auth-service
    env_file:
      - ../../services/auth-service/.env
    environment:
      PORT: 3001
      NODE_ENV: development
      DB_HOST: ev-postgres-auth
      DB_PORT: 5432
      DB_NAME: ev_auth_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - "3001:3001"
    depends_on:
      postgres-auth:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - kong-net
    restart: unless-stopped

  # User Service
  ev-user-service:
    build:
      context: ../../services/user-service
      dockerfile: Dockerfile
    image: user-service:v1.0.0
    container_name: ev-user-service
    env_file:
      - ../../services/user-service/.env
    environment:
      PORT: 3002
      NODE_ENV: development
      DB_HOST: ev-postgres-user
      DB_PORT: 5432
      DB_NAME: ev_user_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      AUTH_SERVICE_URL: http://auth-service:3001
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - "3002:3002"
    volumes:
      - user-service-exports:/app/exports
    depends_on:
      postgres-user:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      ev-auth-service:
        condition: service_started
    networks:
      - kong-net
    restart: unless-stopped

## Analytics-service
  analytics-service:
    build:
      context: ../../services/analytics-service
      dockerfile: Dockerfile
    image: analytics-service:v1.0.0
    container_name: analytics-service
    ports:
      - "3000:3000"
    env_file:
      - ../../services/analytics-service/.env
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - analytics-database
    command: npm run dev
    networks:
      - kong-net

  analytics-database:
    image: mysql:8.0
    container_name: mysql-evcs
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ev_charging
    ports:
      - "3308:3306"
    volumes:
      - ../../services/analytics-service/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - kong-net

## RabbitMQ service
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kong-net

  rabbitmq-service:
    build:
      context: ../rabbitmq
      dockerfile: Dockerfile
    image: rabbitmq-service:v1.0.0
    container_name: rabbitmq-service
    restart: always
    depends_on:
      - rabbitmq
    environment:
      - EXCHANGE_NAME=ev_charging_exchange
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    networks:
      - kong-net

## Kong gateway
  kong-database:
    image: postgres:9.6
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong-data:/var/lib/postgresql/data
    networks:
      - kong-net

  kong-migrations:
    image: kong:3.7
    container_name: kong-migrations
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
    networks:
      - kong-net

  kong:
    image: kong:3.7
    container_name: kong
    restart: always
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    ports:
      - "8000:8000" # proxy
      - "8443:8443" # proxy SSL
      - "8001:8001" # admin API
      - "8444:8444" # admin SSL
    networks:
      - kong-net

  # Apache nifi and warehouse database
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "9443:9443"
    environment:
      - NIFI_WEB_HTTPS_PORT=9443
    volumes:
      - nifi-data:/opt/nifi/nifi-current
    networks:
      - kong-net

  warehouse-database:
    image: mysql:8.0
    container_name: warehouse-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: warehouse
    ports:
      - "3309:3306"
    command: >
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --init-connect='SET NAMES utf8mb4;'
      --skip-character-set-client-handshake
    volumes:
      - warehouse-data:/var/lib/mysql
    networks:
      - kong-net

volumes:
  station-data:
  charging-data:
  kong-data:
  postgres-auth-data:
  postgres-user-data:
  pgadmin-data:
  mysql_data:
  user-service-exports:
  reservation-data:
  rabbitmq-data:
  payment-db-data:
  nifi-data:
  warehouse-data:

networks:
  kong-net:
    driver: bridge

