
services:
  api:
    build: .
    container_name: analytics-service
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mysql
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
    command: npm run dev

  mysql:
    image: mysql:9.1
    container_name: mysql-evcs
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ev_charging
    ports:
      - "3307:3306"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
